### ISSUE TITLE
Cabana displays all messages as 8 byte

### ISSUE THREAD

**Issue by energee** [commaai/cabana-issues#22]
I'm sure this a known bug but cabana displays (and outputs logs) that show all can messages as 8 bytes; if the value is \0x12\0xa3, it displays as: \0x12\0xa3\0x00\0x00\0x00\0x00\0x00\0x00. On some cars, like Hondas, we can determine which are shorter because counter/checksum is on the last byte but this not true for every car and it could potentially be hard to determine how large the packets are.

**Comment by jyoung8607** [comment]
If it was a UI problem, this has been fixed at some point. As an example, message Klemmen_Status_01 0x3c0 on VW MQB is a 4 byte message and properly displays as such in Cabana, either with -/-- instead of 0/00 for the missing bits/bytes, or (if a 4-byte DBC is loaded) shows those bytes missing entirely.

However, the downloaded log does still seem to contain trailing 00s.

**Comment by pd0wm** [comment]
Downloaded logs look fine now.
